### ISSUE TITLE
Async giving errors

### ISSUE THREAD

**Issue by KTibow** [replit/replit-py#115]
I was storing large amounts of data, and it started getting too laggy. So I tried to implement the async database with this code:
```python3
from replit.database import AsyncDatabase

db = AsyncDatabase(os.environ.get("REPLIT_DB_URL"))
```
However, just doing `await db.keys()` is giving me this error:
```
[2021-10-24 21:09:26 +0000] [8570] [ERROR] Exception occurred while handling uri: 'http://flips.ml/history'
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    class Sanic(BaseSanic, metaclass=TouchUpMeta):
  File "main.py", line 281, in get_history
    keys = sorted(list(await db.keys()))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 208, in keys
    return await self.list("")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 178, in list
    async with self.sess.get(self.db_url, params=params) as response:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/client.py", line 448, in _request
    with timer:
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/aiohttp/helpers.py", line 635, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```
How could I fix this?

**Comment by KTibow** [comment]
I was using replit's database to routinely store archived data, and I believe there's a size limit per key.

**Comment by Scoder12** [comment]
Correct.
