### ISSUE TITLE
Can't use `web.auth.name` in view parameters

### ISSUE THREAD

**Issue by DillonB07** [replit/replit-py#120]
Here's my function throwing the issue:

```py
@app.route("/<user>")
@web.authenticated
def user(user: str = web.auth.name):
    if web.auth.name == 'DillonB07':
        return render_template(f'files/{user}/index.html')
    else:
        return render_template(f'files/{web.auth.name}/index.html')
```

Here's a runtime log:

```py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    def user(user: str = web.auth.name):
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/replit/web/__init__.py", line 14, in <lambda>
    auth = LocalProxy(lambda: ReplitAuthContext.from_headers(flask.request.headers))
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/werkzeug/local.py", line 436, in __get__
    obj = instance._get_current_object()
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/werkzeug/local.py", line 565, in _get_current_object
    return self.__local()  # type: ignore
  File "/home/runner/File-Sharing/venv/lib/python3.8/site-packages/flask/globals.py", line 33, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

As I understand it, the issue comes from using `web.auth.name` as a default for a parameter in my view. Is this a bug, or am I just not allowed to do that?

Rest of the code: https://gist.github.com/DillonB07/dbb95c4908499d9ba34f3ef1aca6778b

**Comment by DillonB07** [comment]
Yeah, that's the solution I ended up with. 

Why doesn't this work though?

**Comment by Scoder12** [comment]
The reason is that it is a special variable whose value changes everytime
it is accessed.
