### ISSUE TITLE
AttributeError: 'Database' object has no attribute '_refresh_timer'

### ISSUE THREAD

**Issue by fw-real** [replit/replit-py#217]
i keep getting this error on running http db calls with replit db, full traceback:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Chiranjeevi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Chiranjeevi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1431, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\Chiranjeevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\replit\database\database.py", line 570, in _watchdog
    return self.close()
           ^^^^^^^^^^^^
  File "C:\Users\Chiranjeevi\AppData\Local\Programs\Python\Python312\Lib\site-packages\replit\database\database.py", line 763, in close
    if self._refresh_timer:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Database' object has no attribute '_refresh_timer'

**Comment by fw-real** [comment]
fixed
