### ISSUE TITLE
Bug/Typo - millaseconds is an invalid keyword argument for new

### ISSUE THREAD

**Issue by techpixel** [replit/replit-py#6]
```
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    duration = playingNow.duration.total_seconds()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/audio/__init__.py", line 131, in duration
    return timedelta(millaseconds=self.__payload["Duration"])
TypeError: 'millaseconds' is an invalid keyword argument for __new__()
```

I tried to get the duration but I encountered an error. Seems like a typo: `millaseconds` should be spelled `milliseconds`.

**Comment by Scoder12** [comment]
Fixed in dev, thanks for reporting!
