### ISSUE TITLE
replit db error

### ISSUE THREAD

**Issue by maverick-dev-55** [replit/replit-py#91]
``` batch
[2021-06-06 17:11:50,692] ERROR in app: Exception on /signup [GET]
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "main.py", line 80, in signup
    user.signup()
  File "main.py", line 21, in signup
    db[self.name] = self.data
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 484, in __setitem__
    self.set(key, value)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 493, in set
    self.set_raw(key, _dumps(value))
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/replit/database/database.py", line 56, in dumps
    return json.dumps(val, separators=(",", ":"), cls=DBJSONEncoder)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
```

**Comment by Scoder12** [comment]
Do you know what a circular reference is?

**Comment by maverick-dev-55** [comment]
no, not at all

**Comment by Scoder12** [comment]
Don't be afraid to google it https://stackoverflow.com/q/14249115/9196137

**Comment by Scoder12** [comment]
Actually that isn't a very good example so I will explain it. A circular reference is when the data you are trying to encode has a reference to the data itself inside of it, like this:
```py
foo = {"a": 1}
foo["foo"] = foo
```
Now if we try to represent this as JSON, we can't because the object essentially has infinite size. Everytime you try to serialize the foo key it has another foo object inside of it, making it impossible. 

You can fix this by ensuring there are no circular references in your code.

**Comment by maverick-dev-55** [comment]
Ok i get it

**Comment by Scoder12** [comment]
OK good, reopen if you can't figure it out

**Comment by Fluffik3666** [comment]
im getting this error with the replit db database ValueError: Circular reference detected
